# Server
server.port=8082

# Application
spring.application.name=upload-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/image
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis Plus
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# File Upload
app.upload.directory=uploads/images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Storage directories
app.storage.uploads-directory=uploads/images
app.storage.processed-directory=C:\\image-storage\\processed

#RabbitMQ configuration to connect to the server
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Actuator / Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.info.build.enabled=true
management.info.env.enabled=true

